FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y bison flex build-essential libffi-dev cmake

COPY . /never
WORKDIR /never/build
RUN cmake ..
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /never/build/never /
